name: 3dcnn
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python
  - pytorch
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - scikit-learn
  - pip
  - pip:
    - prettytable
    - wandb
    - multiprocess
