name: 3dcnn
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python::pytorch
  - pytorch
  - nvidia::cudatoolkit=11.1
  - numpy
  - pandas
  - scikit-learn
  - pip
  - pip:
    - prettytable
    - wandb
    - multiprocess
